server:
  port: 9005


spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081/
          predicates:
            - Path=/products/**

        - id: CartService
          uri: http://localhost:8082/
          predicates:
            - Path=/**
